# Generated by Django 6.0.4 on 2026-04-27 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timeout', models.IntegerField(help_text='Timeout in seconds before alert fires')),
                ('alert_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('paused', 'Paused')], default='up', max_length=10)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
